name: Publish to PyPI

on:
  push:
    branches:
      - main  # Ou qualquer branch principal que você queira usar para publicação

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Check Poetry version
        run: poetry --version  # Verifica a versão do Poetry

      - name: Install dependencies
        run: poetry install

      - name: Configure PyPI repository
        run: poetry config repositories.pypi https://upload.pypi.org/legacy/  # Endpoint correto para upload

      - name: Configure Poetry with PyPI token
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_TOKEN }}"  # Passando o secret do GitHub com a sintaxe correta

      - name: Verify Poetry configuration
        run: |
          echo "Verificando configuração do Poetry..."
          poetry config --list  # Verifica a configuração do Poetry para ver se o token foi setado corretamente
          poetry show  # Mostra os pacotes do projeto para verificar se tudo está configurado corretamente

      - name: Publish to PyPI
        run: |
          echo "Publishing to PyPI..."
          poetry publish --build --repository pypi  # Publica para o PyPI
